### ISSUE TITLE
crap

### ISSUE THREAD

**Issue by phil123456** [GreyGnome/AdaEncoder#4]
crappiest library ever

bits are missing and why do you use bytebuffer crap just to print serial in an example

what a waste of time

**Comment by GreyGnome** [comment]
Thanks Phil. Your refund is in the mail.

**Comment by GreyGnome** [comment]
One wonders why phil spent his time commenting on a 6 year old library, filling the universe with more of his angst and nastiness. Oh well, one will never know because he's dead to me and I like it that way. Good luck, phil, and may you one day find it in your heart to be at least a little decent.
